language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t gdachs/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true gdachs/docker-react npm run test